# Generated by Django 6.1 on 2026-08-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('revised', 'Revised'), ('finalized', 'Finalized'), ('sent', 'Sent'), ('accepted', 'Accepted')], default='draft', max_length=10),
        ),
    ]
