# Generated by Django 6.1 on 2026-08-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_alter_quote_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VATSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=15.0, help_text='VAT rate as a percentage, e.g. 15.00 for 15%', max_digits=5)),
                ('vat_enabled', models.BooleanField(default=True, help_text='If off, quotes are generated and shown without VAT')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
