# Generated by Django 6.1 on 2026-08-18 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_vatsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('client_brief', models.TextField(blank=True)),
                ('snapshot_text', models.TextField(help_text='The generated_quote_text at the time of this snapshot')),
                ('status_at_time', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='quotes.quote')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
